repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.8.3
  hooks:
    # Formaters
    - id: go-fmt
    - id: go-imports

    # Linting
    - id: go-lint
    - id: golangci-lint

    # Code Quality
    - id: go-vet
    - id: go-mod-tidy

    # Testing
    - id: go-test
